services:
  pack-builder:
    image: buildpacksio/pack:latest
    volumes:
      - .:/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    environment:
      - DOCKER_CONFIG=/workspace/.docker
      - PACK_HOME=/workspace/.pack
    command: >
      build eu.gcr.io/halfpipe-io/engineering-enablement/spring-music
      --path ./build/libs
      --builder paketobuildpacks/builder-jammy-base
      --env BP_SPRING_CLOUD_BINDINGS_DISABLED=true
      --env BP_JVM_VERSION=21
      --publish